plugins:
  github_linkback_enabled:
    default: false
  github_linkback_projects:
    default: ""
    type: list
  github_linkback_access_token:
    default: ''
  github_badges_enabled:
    default: false
  github_badges_repo:
    default: ''
  github_permalinks_enabled:
    default: false
